[build]
  # Build command for Next.js application
  command = "npm run build"
  
  # Publish directory (Next.js output)
  publish = ".next"
  
  # Build environment
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Next.js build environment
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for SPA routing and API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle Next.js dynamic routes
[[redirects]]
  from = "/create"
  to = "/create"
  status = 200

[[redirects]]
  from = "/meme/*"
  to = "/meme/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.supabase.co https://api.netlify.com; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self';"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# Manifest headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/manifest+json"

# API routes headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Functions configuration
[functions]
  # Node.js version for functions
  node_bundler = "esbuild"
  
  # Function timeout
  timeout = 30

# Edge functions (if needed)
[[edge_functions]]
  function = "api"
  path = "/api/*"

# Build optimization
[build.processing]
  # Image optimization
  images = true
  
  # CSS optimization
  css = { bundle = true, minify = true }
  
  # JavaScript optimization
  js = { bundle = true, minify = true }
  
  # HTML optimization
  html = { pretty_urls = true }

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SUPABASE_URL = "https://your-production-project.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-production-anon-key"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  NEXT_PUBLIC_SUPABASE_URL = "https://your-staging-project.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-staging-anon-key"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_SUPABASE_URL = "https://your-dev-project.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-dev-anon-key"

# Build hooks
[build.hooks]
  # Pre-build hook
  pre_build = "npm run prebuild"
  
  # Post-build hook
  post_build = "npm run postbuild"

# Form handling
[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/api/:splat"
  status = 200

# Error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/500"
  to = "/500.html"
  status = 500

# PWA support
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

# Image optimization
[build.processing.images]
  compress = true
  quality = 80
  formats = ["webp", "avif"]

# Performance optimization
[build.processing]
  skip_processing = false
  
  # Bundle optimization
  bundle = true
  
  # Minification
  minify = true
  
  # Source maps (disabled for production)
  source_maps = false

# Analytics (optional)
[build.environment]
  # Google Analytics (if using)
  # NEXT_PUBLIC_GA_ID = "your-ga-id"
  
  # Vercel Analytics (if using)
  # NEXT_PUBLIC_VERCEL_ANALYTICS_ID = "your-vercel-analytics-id"

# Custom domains (configure in Netlify dashboard)
# [build.environment]
#   CUSTOM_DOMAIN = "your-domain.com"

# Build matrix (for different Node versions)
[[build.matrix]]
  node_version = ["16", "18", "20"]

# Dependencies
[build.environment]
  # Ensure all dependencies are installed
  NPM_FLAGS = "--legacy-peer-deps"
  
  # Build cache
  NODE_MODULES_CACHE = true
  NPM_CACHE = true 